variables:
  environment: 'Dev'
  workspace: 'workspace-Dev'
  environment_sign_off: 'Dev'
  az_service_connection: 'DEV-POOL'
  db_service_connection: 'DEV-POOL'
  InstrumentationKey: 'ca0e1b13-0e09-4ae6-ac0e-20715a31eb8d'
  ApplicationId: '65ccbacc-c40d-40a9-ab5a-c468e8367191'
  az_agent_pool: 'DEV-POOL'
  service_principal_name: 'service_principal_name_id' # service principal name id/ managed_identitiy for dev environment
  DATABRICKS_HOST: https://dbc-d3262ca8-f788.cloud.databricks.com/browse?o=2232572122829467
  DATABRICKS_INSTANCE_ID: 'dbc-d3262ca8-f788.cloud.databricks.com'
  STORAGE_ACCOUNT_NAME: 'DEV-STORAGE_ACCOUNT_NAME'
  KEY_VAULT: 'dev-kv-1'
  WORKSPACE_ID: "d3262ca8-f788"
  INTERNAL_CATALOG: 'dev_catalog'
  SCHEMA_NAME: "dev_schema"
